### PR TITLE
Do not allocate a task when the value task is completed

### PR DESCRIPTION
**Pull request by danielmarbach**
Caveat: I'm a bit of an FSharp noob. So I might have gotten this wrong

Also I wanted to make this contribution from Rider or VSCode but whenever I did do the changes locally the editor entirely changed the indentation :( So I ended up doing it in the github editor to make sure we don't have a huge diff

### CODE REVIEW

**Comment by kekyo** [comment]
Thank you PR, I read your patch.
Exactly we will dodge Task (or ValueTask) allocation when it was completed, nice work!

On 5fa0d58, I understood it made narrowing scope. But I couldn't understand is it safe...

The scheduler come from SynchContext, and will get bound SynchContext at original code position.
Do you know this scheduler (related SynchContext) equals between before Async.FromContinuations and after callbacking?

**Comment by danielmarbach** [comment]
I removed the commit for now. I was thinking it should be safe since the part should be executed under the current thread but I didn't have enough time to really dig into all the FSharp code in https://github.com/dotnet/fsharp/blob/main/src/fsharp/FSharp.Core/async.fs#L1096

**Comment by kekyo** [comment]
Thank you, merged onto devel branch. I will release 2.2.0 soon.

**Comment by kekyo** [comment]
@danielmarbach Oh sorry, GitHub didn't record contributor when unrelated branch (main --> devel)
I will write you on history section.

**Pull request closed without merging**
